import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Auto-generated sidebar for the `apps` docs plugin instance.
 * Each app folder under `content/apps/<slug>/` becomes a section with its
 * `index.mdx` as the section landing page and any subpages listed below it.
 */
const sidebars: SidebarsConfig = {
  apps: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
