import fs from 'node:fs';
import path from 'node:path';
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * One sidebar per theme folder, so a doc page only shows pages within that
 * theme. Each sidebar id matches the theme slug.
 */
const root = path.resolve(__dirname, 'content/themes');

const slugs = fs.existsSync(root)
  ? fs
      .readdirSync(root, {withFileTypes: true})
      .filter(
        (e) =>
          e.isDirectory() && fs.existsSync(path.join(root, e.name, 'index.mdx')),
      )
      .map((e) => e.name)
  : [];

const sidebars: SidebarsConfig = Object.fromEntries(
  slugs.map((slug) => [slug, [{type: 'autogenerated', dirName: slug}]]),
);

export default sidebars;
