import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Auto-generated sidebar for the `themes` docs plugin instance.
 */
const sidebars: SidebarsConfig = {
  themes: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
